[package]
name = "rustyclip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.34", features = ["yaml"]}
colored = "2.0.0"
rusqlite = { version = "0.27.0" , features = ["bundled"] }
